-- p0dcasters.com: the Postgres schema.
--
-- Generated from the live Turso database with `npx libsql-pg convert-schema`
-- (2026-09-25) and reviewed. Every timestamp is unix seconds in a bigint, as
-- the app writes and compares them; the 0/1 flags (`explicit`, `public`) stay
-- bigint because the app compares them as integers. Idempotent: apply with
--
--   psql "$DATABASE_URL" -f db/schema.pg.sql
--
-- or, without psql, `node scripts/db_sql.mjs --file db/schema.pg.sql`.
--
-- The directory reload (scripts/load_directory.mjs) recreates `podcasts` and
-- `platform_hosts` on every run, so their definitions here and there must
-- agree; the account tables, `refresh_runs`, `submissions` and the profile
-- tables are only ever created here.

create table if not exists users (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at bigint not null,
  last_seen_at bigint
);
create unique index if not exists i_users_email on users(email);

create table if not exists sessions (
  token_hash text primary key,
  user_id bigint not null,
  created_at bigint not null,
  expires_at bigint not null
);
create index if not exists i_sessions_user on sessions(user_id);

create table if not exists login_tokens (
  token_hash text primary key,
  email text not null,
  created_at bigint not null,
  expires_at bigint not null,
  used_at bigint,
  ip text
);
create index if not exists i_login_email on login_tokens(email, created_at desc);
create index if not exists i_login_ip on login_tokens(ip, created_at desc);

create table if not exists credentials (
  id text primary key,
  user_id bigint not null,
  public_key text not null,
  counter bigint not null default 0,
  transports text,
  label text,
  created_at bigint not null,
  last_used_at bigint
);
create index if not exists i_cred_user on credentials(user_id);

-- Keyed by slug, not podcasts.id: the reload reassigns ids.
create table if not exists follows (
  user_id bigint not null,
  slug text not null,
  created_at bigint not null,
  primary key (user_id, slug)
);
create index if not exists i_follows_slug on follows(slug);

-- One row per refresh-pipeline run; what /crawlstats reads.
create table if not exists refresh_runs (
  id bigint generated by default as identity primary key,
  run_key text not null,
  started_at bigint not null,
  finished_at bigint,
  status text not null,
  step text,
  dump_modified text,
  dump_bytes bigint,
  podcast_count bigint,
  prev_count bigint,
  categories text,
  message text,
  log text
);
create unique index if not exists i_runs_key on refresh_runs(run_key);
create index if not exists i_runs_started on refresh_runs(started_at desc);

create table if not exists submissions (
  id text primary key,
  batch_id text not null,
  input text not null,
  feed_url text,
  slug text,
  title text,
  status text not null,
  error text,
  message text,
  podcast text,
  user_id bigint,
  ip_hash text,
  created_at bigint not null,
  resolved_at bigint,
  refreshed_at bigint,
  submitted_by text,
  reviewed_at bigint,
  reviewed_by text,
  reason text
);
create index if not exists i_sub_batch on submissions(batch_id, created_at);
create index if not exists i_sub_feed on submissions(feed_url);
create index if not exists i_sub_status on submissions(status, created_at);
create index if not exists i_sub_ip on submissions(ip_hash, created_at desc);

create table if not exists podcast_profiles (
  slug text primary key,
  overrides text,
  public bigint not null default 1,
  owner_user_id bigint,
  owner_email text,
  owner_principal text,
  claimed_at bigint,
  claim_method text,
  updated_at bigint not null
);
create index if not exists i_profiles_updated on podcast_profiles(updated_at desc);
create index if not exists i_profiles_owner on podcast_profiles(owner_user_id);

create table if not exists profile_sources (
  feed_url text not null,
  source text not null,
  url text,
  body text,
  fetched_at bigint not null,
  primary key (feed_url, source)
);

-- The directory. Rebuilt whole by scripts/load_directory.mjs (staged beside
-- the live table, swapped in one transaction), so this block is the same DDL
-- that script carries.
create table if not exists podcasts (
  id bigint generated by default as identity primary key,
  slug text not null,
  guid text,
  feed_url text not null,
  title text not null,
  description text not null,
  image_url text not null,
  link text,
  host text not null,
  author text,
  owner text,
  explicit bigint not null default 0,
  language text,
  lang_base text,
  category text,
  categories text,
  episode_count bigint not null,
  newest_pubdate bigint not null,
  oldest_pubdate bigint,
  created_on bigint,
  latest_audio text,
  latest_duration bigint,
  generator text,
  per_week double precision,
  score double precision not null
);

create table if not exists platform_hosts (
  host text primary key,
  feeds bigint not null
);

-- Search. The FTS5 index (title, description, author, host; bm25 weights
-- 8/1/3/4) becomes a weighted tsvector: A = title, B = host, C = author,
-- D = description, so ts_rank orders results the way bm25 did. It is an
-- expression index rather than a stored column so `SELECT *` over `podcasts`
-- keeps returning the row the app expects and nothing else; the reload only
-- has to recreate the index. The `simple` configuration tokenises without
-- stemming, like FTS5's unicode61 did, so prefix matches (`term:*`) behave.
create or replace function p0d_search_vector(title text, host text, author text, description text)
  returns tsvector
  language sql immutable parallel safe
as $$
  select setweight(to_tsvector('simple', coalesce(title, '')), 'A')
      || setweight(to_tsvector('simple', coalesce(host, '')), 'B')
      || setweight(to_tsvector('simple', coalesce(author, '')), 'C')
      || setweight(to_tsvector('simple', coalesce(description, '')), 'D')
$$;

create unique index if not exists i_slug on podcasts(slug);
create index if not exists i_cat on podcasts(category);
create index if not exists i_lang on podcasts(lang_base);
create index if not exists i_host on podcasts(host);
create index if not exists i_score on podcasts(score desc);
create index if not exists i_new on podcasts(newest_pubdate desc);
create index if not exists i_search on podcasts using gin (p0d_search_vector(title, host, author, description));
